# Travis configuration for gardener unit tests.
language: go
services:
  - docker

go:
   - 1.15

###########################################################################
before_install:
- echo Branch is ${TRAVIS_BRANCH} and Tag is ${TRAVIS_TAG}

# Coverage tools
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge

# Install gcloud, for integration tests.
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
- source "${HOME}/google-cloud-sdk/path.bash.inc"

# Install test credentials for authentication:
# * gcloud commands will use the activated service account.
# * Go libraries will use the GOOGLE_APPLICATION_CREDENTIALS.
- if [[ -n "$SERVICE_ACCOUNT_mlab_testing" ]] ; then
    echo "$SERVICE_ACCOUNT_mlab_testing" > $TRAVIS_BUILD_DIR/creds.json ;
    export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/creds.json ;
    travis/activate_service_account.sh SERVICE_ACCOUNT_mlab_testing ;
    cd $TRAVIS_BUILD_DIR/testfiles ;
    ./sync.sh ;
    cd $TRAVIS_BUILD_DIR ;
  fi

install:
# Install dependencies for all tests.
- cd $TRAVIS_BUILD_DIR
- go get -v -t ./...
- go get -v -tags=integration -t ./...

before_script:
# Remove boto config; recommended for datastore emulator.
- sudo rm -f /etc/boto.cfg

# Install and run datastore emulator.
- gcloud components install beta
- gcloud components install cloud-datastore-emulator
- gcloud beta emulators datastore start --no-store-on-disk &
- sleep 2 # allow time for emulator to start up.
- $(gcloud beta emulators datastore env-init)

script:
# Run all the non-integration unit tests.
- cd $TRAVIS_BUILD_DIR
- go test -v -coverprofile=_unit.cov ./...

# Run all integration unit tests. Some tests are repeated, but this preserves
# coverage statistics.
- if [[ -n "$SERVICE_ACCOUNT_mlab_testing" ]] ; then
    go test -v -coverprofile=_integration.cov ./... -tags=integration ;
  fi

# Also run some concurrency sensitive tests with -race
- go test -v ./tracker/... ./ops/... -race

# Combine coverage of unit tests and integration tests and send the results to
# coveralls.
- $HOME/gopath/bin/gocovmerge _*.cov > _merge.cov
- $HOME/gopath/bin/goveralls -coverprofile=_merge.cov -service=travis-ci || true  # Ignore failure
