apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-etl-gardener-disk0
  annotations:
    volume.beta.kubernetes.io/storage-class: "fast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10GB