---
start_date: 2019-08-01
tracker:
  stale_timeout: 24h  # Not yet implemented
  retention_timeout: 12h  # Not yet implemented
monitor:
  polling_interval: 1m
sources:
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: ndt7
  target: tmp_ndt.ndt7
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: annotation
  target: tmp_ndt.annotation
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: ndt5
  target: tmp_ndt.ndt5
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: tcpinfo
  # filter: .*T[0-9]{6}\.00.*Z.* # Process only 1/100 of data.
  target: tmp_ndt.tcpinfo
