apiVersion: v1
  kind: Service
  metadata:
    name: etl-gardener-service
    namespace: default
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: etl-gardener-server
    sessionAffinity: None
    type: LoadBalancer
